enum actionTypes {
  SHOW_ERROR_MESSAGE = 'SHOW_ERROR_MESSAGE',
  HIDE_ERROR_MESSAGE = 'HIDE_ERROR_MESSAGE',
  SET_DQL_RESPONSE = 'SET_DQL_RESPONSE',
  SET_DQL_EXPLAIN = 'SET_DQL_EXPLAIN',
}

export default actionTypes;
