enum actionTypes {
  SHOW_NOTIFICATION = 'SHOW_NOTIFICATION',
  HIDE_NOTIFICATION = 'HIDE_NOTIFICATION',
  SHOW_ERROR_MESSAGE = 'SHOW_ERROR_MESSAGE',
  HIDE_ERROR_MESSAGE = 'HIDE_ERROR_MESSAGE',
  SET_DOMINO_RESPONSE = 'SET_DOMINO_RESPONSE',
}

export default actionTypes;
